### PR TITLE
Add italian language

### PR DESCRIPTION
**Pull request by bovirus**
@valnoxy 

Please check and merge. Thanks.

### CODE REVIEW

**Comment by valnoxy** [comment]
LGTM but please update the ResourseDirectory to match with the newest commit. See [here](https://github.com/valnoxy/checkip/commit/89fdda30459468aea73fd8ea19818af9b0a5ab9c#diff-3ad9d3ac0aed661ce2cb5d0fd8532356246e24fcc94ee18e853f1733242c8018).

**Comment by bovirus** [comment]
@valnoxy

Did you check here ?

https://github.com/bovirus/checkip/tree/develop/CheckIP.Windows/CheckIP/Localization

I created the relative file requested. And it's in PR.
I etsted the new exe multilangueg compiling in VSC ed it's OK.

**Comment by bovirus** [comment]
@valnoxy 

Did you check ehere?

**Comment by bovirus** [comment]
@valnoxy 

Modify Inno Setup script toa dd gemran and ityalian languages.
Fixed some issues in Inno Setup script:
Make most of the variables in logical order for a better and easier maintenance.
Fixed issues about output name (installer exe).

**Comment by valnoxy** [comment]
> @valnoxy
> 
> Did you check here?
> 
> https://github.com/bovirus/checkip/tree/develop/CheckIP.Windows/CheckIP/Localization
> 
> I created the relative file requested. And is in PR.

Yes, but there are 5 new strings that need to be translated. The link highlights the new changes.

**Pull request closed without merging**
